matrix:
  include:
    - language: ruby
      rbenv:
        - 1.1.1
      script:
        - bundle exec rspec

    - language: node_js
      node_js:
        - "6"
        - "7"
      script:
        - npm run test
        - npm run eslint-fix
