matrix:
  include:
    - language: ruby
      rbenv:
        - 1.1.1
      config_file: ".rubocop.yml"
      script:
        - bundle exec rspec
        - bundle exec rubocop

    - language: node_js
      node_js:
        - "6"
        - "7"
      script:
        - npm run test
        - npm run eslint
